export type Job={id:string;title:string;company:string;initials:string;color:string;area:string;salary:string;city:string;mode:string;contract:string;first:boolean;skills:string[];description:string;requirements:string[];benefits:string[];expires:string};
export const JOBS:Job[]=[
{id:"sb-001",title:"Assistente administrativo",company:"Grupo Horizonte",initials:"gh",color:"blue",area:"Administrativo",salary:"R$ 1.800 – R$ 2.200",city:"Barro, CE",mode:"Presencial",contract:"CLT",first:false,skills:["Excel","organização","atendimento","planilhas"],description:"Apoie a organização do dia a dia de uma equipe que cresce com a região. Você vai cuidar de documentos, atualizar planilhas e acompanhar rotinas administrativas.",requirements:["Ensino médio completo","Conhecimento básico de planilhas","Organização e boa comunicação"],benefits:["Vale-transporte","Vale-alimentação","Desenvolvimento profissional"],expires:"2026-12-31"},
{id:"sb-002",title:"Consultor de vendas",company:"Casa do Sertão",initials:"cs",color:"orange",area:"Comércio",salary:"R$ 1.650 + comissão",city:"Barro, CE",mode:"Presencial",contract:"CLT",first:true,skills:["vendas","atendimento","comunicação"],description:"Ajude cada cliente a encontrar o que precisa. A rotina envolve atendimento na loja, apresentação de produtos e acompanhamento das vendas.",requirements:["Ensino médio completo","Facilidade para conversar e ouvir","Disponibilidade em horário comercial"],benefits:["Comissão por vendas","Treinamento inicial","Vale-transporte"],expires:"2026-12-31"},
{id:"sb-003",title:"Técnico em redes",company:"Conecta Cariri",initials:"cc",color:"purple",area:"Tecnologia",salary:"R$ 2.200 – R$ 2.800",city:"Barro, CE",mode:"Presencial",contract:"CLT",first:false,skills:["TCP/IP","cabeamento","MikroTik","roteadores","suporte","infraestrutura"],description:"Conecte pessoas e negócios. Atue na instalação, configuração e manutenção de redes, com suporte próximo aos clientes da região.",requirements:["Curso técnico em redes ou experiência equivalente","Conhecimento de TCP/IP e cabeamento","Experiência com configuração de roteadores"],benefits:["Vale-alimentação","Capacitação técnica","Equipamentos de trabalho"],expires:"2026-12-31"},
{id:"sb-004",title:"Designer gráfico",company:"Estúdio Vereda",initials:"ev",color:"green",area:"Tecnologia",salary:"R$ 2.000 – R$ 3.000",city:"Juazeiro do Norte, CE",mode:"Remoto",contract:"PJ",first:false,skills:["design","Figma","Photoshop","tipografia","portfólio"],description:"Transforme ideias em comunicação visual. Crie peças digitais, identidades e materiais de campanha com uma equipe colaborativa.",requirements:["Portfólio com projetos de design","Conhecimento de tipografia e composição","Domínio de uma ferramenta gráfica"],benefits:["Trabalho remoto","Horários flexíveis","Trocas criativas com a equipe"],expires:"2026-12-31"},
{id:"sb-005",title:"Auxiliar de logística",company:"Rota Nordeste",initials:"rn",color:"orange",area:"Serviços",salary:"R$ 1.700 – R$ 1.950",city:"Brejo Santo, CE",mode:"Presencial",contract:"CLT",first:true,skills:["estoque","organização","logística","conferência"],description:"Participe da organização de estoque, separação de pedidos e conferência de mercadorias. A empresa oferece treinamento para a função.",requirements:["Ensino médio completo","Atenção aos detalhes","Disponibilidade em horário comercial"],benefits:["Treinamento","Vale-transporte","Vale-alimentação"],expires:"2026-12-31"},
{id:"sb-006",title:"Aprendiz administrativo",company:"Grupo Horizonte",initials:"gh",color:"blue",area:"Administrativo",salary:"R$ 850 – R$ 1.100",city:"Barro, CE",mode:"Presencial",contract:"Aprendizagem",first:true,skills:["organização","atendimento","informática"],description:"Comece sua trajetória com acompanhamento. Conheça as rotinas de escritório, participe de atividades de apoio e desenvolva novas habilidades.",requirements:["Ensino médio em andamento ou concluído","Interesse em aprender rotinas administrativas","Disponibilidade para a jornada de aprendizagem"],benefits:["Formação profissional","Vale-transporte","Acompanhamento de um tutor"],expires:"2026-12-31"}
];
export const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
export function searchJobs(jobs:Job[],query="",area="Todas as áreas",city="Todas",mode="Todas"){
const q=normalize(query);
return jobs.filter(j=>new Date(j.expires+"T23:59:59")>=new Date()&&(area==="Todas as áreas"||j.area===area)&&(city==="Todas"||j.city===city)&&(mode==="Todas"||j.mode===mode)&&(!q||(q==="primeiro emprego"?j.first:normalize([j.title,j.company,j.area,...j.skills,j.first?"primeiro emprego":""].join(" ")).includes(q))));
}
export type Profile={name:string;role:string;city:string;summary:string;experience:string;education:string;skills:string;availability:string};
export const EMPTY_PROFILE:Profile={name:"",role:"",city:"Barro, CE",summary:"",experience:"",education:"",skills:"",availability:"Presencial"};
export const TALENTS=[
{id:"t1",name:"Sofia Oliveira",role:"Técnica em redes",initials:"SO",color:"purple",skills:["TCP/IP","Cabeamento","MikroTik","Suporte"],experience:"2 anos em suporte e redes",city:"Barro, CE",education:"Técnico em Redes de Computadores",stage:"Em análise"},
{id:"t2",name:"Lucas Santos",role:"Designer gráfico",initials:"LS",color:"orange",skills:["Figma","Photoshop","Tipografia","Identidade visual"],experience:"3 anos em design",city:"Juazeiro do Norte, CE",education:"Tecnólogo em Design Gráfico",stage:"Novos"},
{id:"t3",name:"Mariana Costa",role:"Assistente administrativo",initials:"MC",color:"green",skills:["Excel","Organização","Atendimento","Planilhas"],experience:"1 ano em rotinas administrativas",city:"Barro, CE",education:"Ensino médio completo",stage:"Entrevista"}
];
export const STAGES=["Novos","Em análise","Informações solicitadas","Pré-selecionados","Entrevista","Proposta","Contratado","Não selecionado","Desistente"];
